# Generated by Django 3.2.6 on 2021-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_NO', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Balance', models.IntegerField(default=0)),
            ],
        ),
    ]
