# Generated by Django 3.2.6 on 2021-08-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_tansfers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tansfers',
            new_name='Transfers',
        ),
    ]
